    <div class="">
    <div id="breadcrumdiv">
    <div class="breadcrumbs"><span class="firstbreadcrumb" onclick="window.location='http://localhost/beta/hrm/index.php'">Home</span> <span class="arrows">&rsaquo;</span> <span>HR</span> <span class="arrows">&rsaquo;</span> <a href="http://localhost/beta/hrm/index.php/employee" >Employees</a></div>    </div>
    
	
    <div id="pageshortcutdiv" class="shortcut_div help_appri_list">
			
        <div id="pageshortcut" class ="sprite shortcut-icon " onclick="createorremoveshortcut(14,1)">Pin to shortcuts</div>    </div>
		
        </div><div id="maincontentdiv">	
        <div id="dialog-confirm" style="display:none;">
            <div class="newframe-div">
                <div class="new-form-ui height32">
                    <div class="division">
                        <input maxlength="12" id="number_value" name="number_value" type="text">
                    </div>
                    <span class="errors" id="errors-contactnumber"></span>
                </div>
            </div>
        </div>
    									
        <div id="empstatus-alert" style="display:none;">
            <div class="newframe-div"><div id="empstatusmessage"></div></div>
        </div>
    									
        <div id="empleaves-alert" style="display:none;">
            <div class="newframe-div"><div id="empleavesmessage"></div></div>
        </div>									
<div>

<!-- For excel Upload -->
<div class="profile-tabs-right-2">
    <div class="flt_right">
      	
        <div class="actions_div">

            <span class="uploadbut_exel uploadbutsel flt_left marginfiv   " id="upload_custom_div">Import Employees</span>
			<a target="_blank" href="http://localhost/beta/hrm/public/downloads/import_employees.xlsx" class="importformatlink flt_left">Import format</a>
			<a target="_blank" href="http://localhost/beta/hrm/public/downloads/importguide.pdf" class="importformatlink flt_left">Help</a>
            <div id="loaderimgprofile" style="display:none;"><img src="http://localhost/beta/hrm/public/media/images/loaderwhite_21X21.gif" style="width:21px; height: 21px; float: none; "></div>								
        </div>                 					
    </div>
    <input id="uploadimagepath" name="uploadimagepath" value="" type="hidden">
    <input name="emp_excel" value="" type="hidden">							    	
               				                        					
</div>
</div>

<span id="error_message"></span>
<div id="upload_error" style="display:none;clear:both;"></div>	
<!-- End excel Upload -->
<div id="grid_employee" class="all-grid-control">
<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;"></div><div class="table-header"><span>Employees</span><input title="Add" onclick="window.location.href=&quot;http://localhost/beta/hrm/index.php/payrollgroup/add&quot;" value="Add Record" class="sprite addrecord" type="button"></div><div class="slimScrollDiv" style="position: relative; overflow: hidden; width: 250px; height: auto;"><div id="employee" class="details_data_display_block newtablegrid" style="overflow: hidden; width: 250px; height: auto; background: rgb(204, 204, 204) none repeat scroll 0% 0%; padding-bottom: 10px;">
        <table class="grid" width="100%" cellspacing="0" cellpadding="4" border="0" align="center">
        <thead><tr><th width=90><span class='action-text'>Action</span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Payroll group name</a></span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Assigned employees</a> </span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Payroll Categories</a> </span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Salary preferences</a> </span></th>
               
        </thead><tbody>
            <tr onclick="selectrow(employee,this);" class="row1">
                <td>
                    <div class="grid-action-align">
										<a href="http://localhost/beta/hrm/index.php/payrollgroup/viewpayrollgroup" name="95" class="sprite view" title="View"></a>
										<a href="http://localhost/beta/hrm/index.php/payrollgroup/editpayrollgroup" name="95" class="sprite edit" title="Edit"></a>
										
                    </div>
                </td>
                <td><span title="adam">Bi-weekly</span></td>
                <td><span title="doonn">6</span></td>
                <td><span title="adam@gmail.com">CAT1, DA, CAT3, CAT5, CAT4, WA</span></td>
                <td><span title="EMP9876">Salaried - Bi-weekly</span></td>
               </tr>
            
            <tr onclick="selectrow(employee,this);" class="row2">
                <td><div class="grid-action-align">
										<a href="http://localhost/beta/hrm/index.php/employee/view/id/75" name="75" class="sprite view" title="View"></a>
										<a href="http://localhost/beta/hrm/index.php/employee/edit/id/75" name="75" class="sprite edit" title="Edit"></a>
										
		    </div>
                </td>
                <td><span title="Adrienne">Monthly payroll</span></td>
                <td><span title="Pickles">15</span></td>
                <td><span title="Adrienne_sharad@gmail.com">CAT1, CAT2, CAT3, CAT4, CAT5</span></td>
                <td><span title="EMP142">Salaried - Bi-monthly</span></td>
                </tr>
			
                <tr onclick="selectrow(employee,this);" class="row2">
                <td><div class="grid-action-align">
										<a href="http://localhost/beta/hrm/index.php/employee/view/id/75" name="75" class="sprite view" title="View"></a>
										<a href="http://localhost/beta/hrm/index.php/employee/edit/id/75" name="75" class="sprite edit" title="Edit"></a>
										
		    </div>
                </td>
                <td><span title="Adrienne">weekly</span></td>
                <td><span title="Pickles">0</span></td>
                <td><span title="Adrienne_sharad@gmail.com">CAT1, DA, CAT5</span></td>
                <td><span title="EMP142">Salaried - Weekly</span></td>
                </tr>
			
            </tr>
            </tbody>
        </table>            
        <script type="text/javascript" language="javascript">
                $(document).ready(function(){
                                    
                                    
                                    if($('.searchtxtbox_employee').is(':visible'))
                                    {
                                        
                                        $('#search_tr_employee').show();	
                                    }
                                    else 
                                    {
                                        
                                        $('#search_tr_employee').hide();	
                                           
                                    }
                                    });
                </script> 
</div><div class="slimScrollBar ui-draggable" style="background: rgb(32, 139, 189) none repeat scroll 0% 0%; height: 7px; position: absolute; bottom: 1px; opacity: 1; border-radius: 7px; z-index: 99; width: 443.069px; display: none;"></div><div class="slimScrollRail" style="width: 100%; height: 7px; position: absolute; bottom: 1px; display: none; border-radius: 7px; background: rgb(51, 51, 51) none repeat scroll 0% 0%; opacity: 0.2; z-index: 90;"></div></div>
<div class="table-btm">
		
	<div class="table-buttons">
		<input title="Refresh" onclick="refreshgrid(&quot;employee&quot;,&quot;No&quot;,&quot;&quot;);" value="Refresh Grid" class="sprite refresh-grid" type="button">
				<input value="" id="formGridId" type="hidden">
		<input value="No" id="dashboardcall" type="hidden">
		<input value="ASC" id="sortval_employee" type="hidden">
		<input value="firstname" id="byval_employee" type="hidden">
		<input value="" id="pd_category_id_employee" type="hidden">
     </div>   
     <div class="table-buttons table-buttons-duplicate">
		<input title="Refresh" onclick="refreshgrid(&quot;employee&quot;,&quot;No&quot;,&quot;&quot;);" value="Refresh Grid" class="sprite refresh-grid" type="button">
		     </div>
<div class="pagination_block">
	<div class="records_block">
		<div class="page_txt">
        <span>Records per page</span>
		<div class="records_number-drop-down">			
			<select class="records_input_employee table_inputs not_appli clearall fltleft" id="perpage_employee" name="perpage_employee" onchange="javascript:getAjaxgridData('payrollgroup','No')">
				<option value="10">10</option>
				<option value="20" selected="">20</option>
				<option value="50">50</option>
				<option value="100">100</option>
				<option value="150">150</option>
				<option value="200">200</option>
			</select>
		</div>
			<input id="objname" value="employee" type="hidden">			
         </div>    
			<div class="page_txt" style="display:none;">
				<span>Page</span> 
				<div class="records_number"><input class="gotopage_input_employee" value="1" name="gotopage" type="text"></div>
					<input value="›" class="sprite  records_go_btn" onclick="javascript:getAjaxgridData('employee','No')" type="button">			
			</div>
		
	</div>
		<div class="pagination_view">
		<div class="pagination" id="pagination_employee">
			<a href="/?page=1" class="first disabled" data-action="first"><span class="sprite first-1"></span></a>
			<a href="/?page=1" class="previousNew disabled" data-action="previous"><span class="sprite prev-1"></span></a>
			<input id="pagenotext" data-max-page="40" type="text">
			<a href="/?page=2" class="nextNew" data-action="next"><span class="sprite next-1"></span></a>
			<a href="/?page=5" class="last" data-action="last"><span class="sprite last-1"></span></a>
        </div>
	</div>
	</div>
	 
</div>
