<?php $months = array('1' => 'Jan', '2'=>'Feb', '3'=>'Mar', '4'=>'Apr', '5'=>'May', '6'=>'Jun', '7'=>'Jul', '8'=>'Aug', '9'=>'Sep', '10'=>'Oct', '11'=>'Nov', '12'=>'Dec');?>
<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/

//echo '<pre>';print_r($this->messages); //die;

if (count($this->messages)) {?><style>#messageData{color:green;}</style>
	<div id="dispmsgemp" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array("1");				
				//$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
                                if(is_array($message)){
                                    echo '<pre>';
                                    print_r($message);
                                } else {
                                    echo $message;
                                }
				echo "</div></div>";
			} 
		?>
	</div>
	
<?php }	
/*if($this->dataArray[0]['emptyroles'] == 1)
{
 ?>
	 <div class="ml-alert-1-info m1-info-set">
		<div class="style-1-icon info"></div>
			Employees grid will not work as Roles are not added yet.
	</div>
 <?php	} else	{*/	?>




<?php
if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
?>

<?php
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;
       
//} ?>
<form method="post" name="frm_selected_emp_ids" id="frm_selected_emp_ids" action="<?php echo BASE_URL.'/payslipemployee/generatebulkpayslip/';?>">
    <input type="hidden" name="emp_ids" id="emp_ids" value="">
    <input type="hidden" name="month" id="month" value="" />
</form>
<script type='text/javascript'>
$(document).ready(function(){
    $('.addrecord').hide();
     //$("tr td:nth-child(6)").html('<a href="<?php echo BASE_URL;?>payslipemployee/generatepayslip" onclick="myFunction(); return false;">Generate</a>');
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgemp').fadeOut('slow');
		},10000);

<?php } ?>

})
</script>

<?php 
if($this->call != "ajaxcall")
{
    if(!empty($this->popConfigPermission))
    {
?>
<script type="text/javascript">
 
function myFunction() {
   //alert("payslip generated successfully");
   successmessage('Payslip generated successfully');
  //$("#error_message").show();
  //$("#error_message").text("Playslip generated successfully");
}
</script>
<?php 
}
}
?>
<script type="text/javascript">
function bulkGenerate(){
    if(is_generated_selectetd()==false){
        jAlert("Please select any employee to generate the payslip.");
        return false;
    }
    jConfirm("Are you sure to generate payslip?","Generate Payslip for Individual Employee",function(r){
        if(r==true){
            $("#frm_selected_emp_ids").submit();
        }else{
             return false;
        }
    });
}    
$(document).ready(function(){
    $('#select_all').on('click',function(){
        if(this.checked){
            $('.checkbox').each(function(){
                this.checked = true;
                //console.log(this.value);
                var selelctedIds=$("#emp_ids").val();
                if(selelctedIds==""){
                    $("#emp_ids").val(this.value);
                }else{
                    selelctedIds=selelctedIds+","+this.value;
                    $("#emp_ids").val(selelctedIds);
                }
            });
        }else{
             $('.checkbox').each(function(){
                this.checked = false;
            });
            $("#emp_ids").val("");
        }
        //var selelctedIds=$("#selected_emp_ids").val();
        //console.log(selelctedIds);
    });
    
    $('.checkbox').on('click',function(){
        if($('.checkbox:checked').length == $('.checkbox').length){
            $('#select_all').prop('checked',true);
        }else{
            $('#select_all').prop('checked',false);
        }
        $("#emp_ids").val("");
        $('.checkbox').each(function(){
            if(this.checked){
                var selelctedIds=$("#emp_ids").val();
                if(selelctedIds==""){
                    $("#emp_ids").val(this.value);
                }else{
                    selelctedIds=selelctedIds+","+this.value;
                    $("#emp_ids").val(selelctedIds);
                }
            }
        });
    });
});

function is_generated_selectetd(){
    var item_checked=false;
    $('.checkbox').each(function(){
        if(this.checked){
            item_checked=true;
        }
    });
    return item_checked;
}

var months = '<?php echo '<div style="width:100%; float:left; margin-top:20px;"><div class="new-form-ui" style="float:left; height:auto;"><label>Select Month :</label><div class="division"><select name="month_val" id="month_val" class="select2" style=" width:100%;" onChange="generatePayslipForMonth(this.value);">';
                                 foreach ($months AS $k => $v):
                                    if($k==(date('n'))){
                                        break;
                                    }
                                    if($k<10){
                                        $k="0".$k;
                                    }
                               echo '<option value="'.$k.'">'.$v.'</option>';
                                endforeach;
                           echo '</select></div></div>'; ?>';

$(document).ready(function(){
    $('.table-header').append(months+'<div class="new-form-ui-submit" style="margin-bottom:10px;float:left; clear:none;margin-top:15px; width:auto;"><button type="button" id="generate" onclick="bulkGenerate();">Generate</button></div></div>');
});


 function generatePayslipForMonth(value){
        var month = $('#month_val').val();
        $('#month').val(month);
    }
</script>