<h4>Payroll Group Details</h4><br><hr>
<div class="new-form-ui">
                                <label class="required">Payroll group name</label>
                                <div class="division">weekly  
<span id="errors-group_name" class="errors"></span>
                                </div> 

                            </div>
<br><h4>Salary Preference</h4><hr>
<div class="new-form-ui">
                                <label class="required">
Employee salary type</label>
                                <div class="division">
                                   Salaried </span>
                                </div> 

                            </div>
<div class="new-form-ui">
                                <label class="required">
Payment frequency</label>
                                <div class="division">
                                    Weekly
                                </div> 

                            </div>
<div class="new-form-ui">
                                <label class="required">
Payslip generation date</label>
                                <div class="division">
                                    Day 1 of every week
                                </div> 

                            </div>

<br><h4>Payroll Categories</h4><hr><br>
<h5>Earnings</h5>
<div id='employee' class='details_data_display_block newtablegrid'>
            <table class='grid' align='center'  width='100%' cellspacing='0' cellpadding='4' border='0'>
                <thead><tr><th width=90><span class='action-text'>Payroll category name ‎(Code)‎</span></th>
                        <th width=90><span class='action-text'>Value</span></th>
                       
                </thead><tbody><tr onclick='selectrow(employee,this);' class='row1'><td ><div class="grid-action-align">
                    Basic Pay ‎(CAT1)‎							
									</div>
                        </td><td ><span  title='Manak' >0.00</span></td></tr>
                </tbody>
	    </table>
    </div>

<br>
<br>
<br>
<h5>Deductions</h5><hr>



        <div id='employee' class='details_data_display_block newtablegrid'>
            <table class='grid' align='center'  width='100%' cellspacing='0' cellpadding='4' border='0'>
                <thead><tr><th width=90><span class='action-text'>Payroll category name ‎(Code)‎</span></th>
                        <th width=90><span class='action-text'>Value</span></th>
                       
                </thead><tbody><tr onclick='selectrow(employee,this);' class='row1'><td ><div class="grid-action-align">
                    Basic Pay ‎(CAT1)‎							
									</div>
                        </td><td ><span  title='Manak' >0.00</span></td></tr>
                </tbody>
	    </table>
    </div>
