<div>
    <div style="float: left;">
        <?php if(isset($this->flash_messages)) :?>
            <div class="notification">
            <?php echo $this->flash_messages ;?>
            </div>    
        <?php endif;?>
    </div>
</div>
<div id="maincontentdiv">	
    <span id="error_message"></span>
    <div id="upload_error" style="display:none;clear:both;"></div>
    <div id="grid_employee" class="all-grid-control">
        <div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;"></div>
        <div class="table-header">
            <span>All Employee</span>
            <div class="new-form-ui" style="float: right;">
                <label>Frequency</label>
                <div class="division">
                    <select name="category_value" id="category_value">
                        <option value="">Select Frequency</option>
                        <option value="">Frequency 1</option>
                        <option value="">Frequency 2</option>
                    </select>
                </div> 
            </div>
        </div>
        
        <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: 250px; height: auto;">
                <div id="employee" class="details_data_display_block newtablegrid" style="overflow: hidden; width: 250px; height: auto; background: rgb(204, 204, 204) none repeat scroll 0% 0%; padding-bottom: 10px;">
                <table class="grid" width="100%" cellspacing="0" cellpadding="4" border="0" align="center">
                    <?php if(!empty($this->AllEmployee)):?>
                    <thead>
                        <tr>
                            <th width=90><span class='action-text'>Employee name</span></th>
                            <th width=90><span class='action-text'>Employee role</span></th>
                            <th width=90><span class='action-text'>Payment frequency</span></th>
                            <th width=90><span class='action-text'>Recent payslip</span></th>
                            <th width=90><span class='action-text'></span></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach($this->AllEmployee As $k => $v): ?>
                        <tr class="row1">
                            <td><span title="<?php echo ucwords($v['userfullname']);?>"><?php echo ucwords($v['userfullname']);?></span></td>
                            <td><span title="<?php echo ucwords($v['rolename']);?>"><?php echo ucwords($v['rolename']);?></span></td>
                            <td>
                                <span title="<?php echo ucwords($v['freqtype']);?>"><?php echo ucwords($v['freqtype']);//.$fDT;?></span>
                            </td>
                            <td></td>
                            <td><a href="#">Generate payslip</a> | <a href="#">View payslips</a></td>
                        </tr>
                        <?php endforeach;?>
                        </tr>
                    </tbody>
                    <?php else:?>
                    <tr>
                        <td colspan="5" style=" text-align: center;"> No record found </td>
                    </tr>
                    <?php endif;?>
                </table>            
                 
            </div>
<div class="slimScrollBar ui-draggable" style="background: rgb(32, 139, 189) none repeat scroll 0% 0%; height: 7px; position: absolute; bottom: 1px; opacity: 1; border-radius: 7px; z-index: 99; width: 443.069px; display: none;"></div><div class="slimScrollRail" style="width: 100%; height: 7px; position: absolute; bottom: 1px; display: none; border-radius: 7px; background: rgb(51, 51, 51) none repeat scroll 0% 0%; opacity: 0.2; z-index: 90;"></div></div>