<?php $months = array('1' => 'Jan', '2'=>'Feb', '3'=>'Mar', '4'=>'Apr', '5'=>'May', '6'=>'Jun', '7'=>'Jul', '8'=>'Aug', '9'=>'Sep', '10'=>'Oct', '11'=>'Nov', '12'=>'Dec');?>
<div id="grid_employee" class="all-grid-control">
    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: 250px; height: auto;">
        <div id="employee1" class="details_data_display_block newtablegrid" style="overflow: hidden; width: 250px; height: auto; padding-bottom: 10px;">
            <table class="grid" width="100%" cellspacing="0" cellpadding="4" border="0" align="center">
                <tr>
                    <td>
                        Select Year : <br />
                        <label>
                            <select name="year" id="year">
                                <?php 
                                    for($i=2000;$i<=date('Y');$i++) {
                                ?>
                                <option value="<?php echo $i;?>" <?php if($i==date('Y')) { ?> selected="selected"<?php } ?>><?php echo $i;?></option>
                                <?php } ?>
                            </select>
                        </label>
                    </td>
                    <td>
                        Select Month : <br />
                        <label>
                            <select name="month" id="month">
                                <?php foreach ($months AS $k => $v):
//                                    if($k==(date('n'))){
//                                        break;
//                                    }
                                    if($k<10){
                                        $k="0".$k;
                                    }?>
                                <option value="<?php echo $k;?>" <?php if($k+1==date('m')) { ?> selected="selected" <?php } ?>><?php echo $v;?></option>
                                <?php endforeach;?>
                            </select>
                        </label>
                    </td>
                    <td>
                        Select Employment Status :<br />
                        <label>
                            <select name="empstatus" id="empstatus" onchange="changeEmpList(this.value);">
                                <option value="">Select Employment Status</option>
                                <?php foreach($this->employmentStatusData AS $k => $v):?>
                                <option value="<?php echo $v['workcodename'];?>"><?php echo $v['statusname'];?></option>
                                <?php endforeach;?>
                            </select>
                        </label>
                    </td>
                    <td>
                        Enter the employee name :<br />
                        <label id="employee_list">
                            <select name="emp_name" id="emp_name">
                                <option value="">Select Employee name</option>
                                <?php foreach($this->all_employees AS $k => $v):?>
                                <option value="<?php echo $v['firstname'].' '.$v['lastname'];?>"><?php echo $v['firstname'].' '.$v['lastname'];?></option>
                                <?php endforeach;?>
                            </select>
                        </label>
                    </td>
                    <td>
                        <div class="new-form-ui-submit">
                            <input type="button" name="filter" id="filter" value="Search">
                        </div>
                    </td>
                    <!--<td>
                        <input type="button" name="estimate" id="estimate" value="Get next month estimate">
                    </td>-->
                </tr>
            </table>
        </div>
        <div id="employee" class="details_data_display_block newtablegrid" style="overflow: hidden; width: 250px; height: auto; padding-bottom: 10px;">
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	
	var ajaxURL='<?php echo BASE_URL;?>viewwpsreport/filter/';
	$.ajax({
		url:ajaxURL,
		type :'POST',
		data:'year='+$('#year').val()+'&month='+$('#month').val()+'&empstatus='+$('#empstatus').val()+'&emp_name='+$('#emp_name').val(),
		success:function(msg){
			$('#employee').html(msg);
		}
	});

    $('#filter').on('click',function(){
        var ajaxURL='<?php echo BASE_URL;?>viewwpsreport/filter/';
        $.ajax({
            url:ajaxURL,
            type :'POST',
            data:'year='+$('#year').val()+'&month='+$('#month').val()+'&empstatus='+$('#empstatus').val()+'&emp_name='+$('#emp_name').val(),
            success:function(msg){
                $('#employee').html(msg);
            }
        });
    });
});

function changeEmpList(value){
    var ajaxURL='<?php echo BASE_URL;?>viewwpsreport/getemployeesbystatus/type/'+value+'/month/'+$('#month').val();
    $.ajax({
        url:ajaxURL,
        success:function(msg){
            $('#emp_name').html(msg);
        }
    });
}
</script>