<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/bootstrap.min.css" />

<style type="text/css">
    .home_menu .menu-head{
        height: 42px;
    }

    #numeric, #formula, #conditionwithformula {
        display:none;
    }
    .error{color: red !important;font-weight: bold !important;}
    .right-block-data{
        min-height: 500px;
        width: 96% !important;
        margin-bottom: 10px;
    }
    
    .left-block-ui-data{
        width: 0 !important;
    }
    
    .logo_img{
        max-width: 100%;
        height: 40px;
        margin-bottom: 10px;
        margin-left: 10px;
        text-align: center;
    }
    
    .panel{
        border-radius: 0;
        border: none;
    }
    
    .year_info{
        margin-bottom: 10px;
        margin-top: 10px;
        font-size: 14px;
    }
    
    .year_info b span{
        font-size: 12px;
    }
    
    .border{
        border-right: 1px solid;
    }
    
    .info div{
        font-weight: bold;
    }
    
    .info div,.earning_deduct div{
        line-height: 24px;
        font-size: 13px;
    }
    
    b{
        font-size: 15px;
    }
    
    .panel-body table th, .panel-body table td{
        font-size: 13px;
    }
    
    .panel-body{
        padding: 0;
    }
    
    .panel{
        box-shadow: none !important;
        margin-bottom: 0;
    }
    
    .table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th{
        padding: 1px 5px;
    }
    
    .newtablegrid table.grid thead th a{
        font-family: 'Roboto Bold',sans-serif !important;
    }
    
    .text-right{
        margin-bottom: 0;
    }
</style>

 <?php //echo $this->headScript()->prependFile($this->baseUrl('\public\scripts\jquery.fileDownload-master\src\Scripts\jquery.fileDownload.js')); ?>

<?php if (empty($this->empdata)) { ?>
    <div class="ml-alert-1-info">
        <div class="style-1-icon info"></div>
        <?php if ($this->rowexist == 'norows') { ?>
            No data found.
        <?php } else { ?>
            Employee inactivated.
        <?php } ?>
    </div>
    <?php
} else {
    ?>
    <?php
    $baseUrl = $this->serverUrl() . $this->baseUrl();

    if (!empty($this->employeedata)) {
        echo $this->employeedetails($this->employeedata, 'view', $this->id);
    }
    //print_r($this->employeedata);
    ?>

<!-- Code by Shuchita -->
<?php
    $salaryPerDay=$this->salarydetails['salary']/30;
    $empLeaveData=$this->empLeaveData;

    if($empLeaveData['emp_leave_limit']>=$empLeaveData['used_leaves']) { 
            $lop=0;
        }else{
            $lop=$empLeaveData['used_leaves']-$empLeaveData['emp_leave_limit'];
        }

        $presentDays=30-$lop;
        $salaryForPresentDays=$presentDays*$salaryPerDay;
        $deductedSalary=$salaryPerDay*$lop;
        $netPay=$this->netPayDetails[0]['net_pay']-$deductedSalary;
?>    

<!-- Code by Shuchita -->
 
<div class="right-block-data right-over-border payslip_div"> 
        <div id="error_message" style="display:none;"></div>
        <!--<div class="ml-alert-1-info m1-info-set">
                <div class="style-1-icon info"></div>Feature will be available soon.
        </div>-->
        <div id="winPrint">
            <div class="slimScrollDiv">
                <div id="empleavesummary" class="details_data_display_block newtablegrid" style="width:100% !important;">
                    <div class="row">
                        <div class="row">
            <div class="col-md-12 text-center">
                <span class="text-left">
                    <?php 
                    $organizationImg = new Zend_Session_Namespace('organizationinfo');
                    //echo '<pre>'; print_r($organizationImg);
                    $hideshowmainmenu = $organizationImg->hideshowmainmenu;
                    $orgLogoImg = MEDIA_PATH.'images/hrms-logo-new.PNG';
                    //echo '$orgLogoImg : '.$orgLogoImg;
                    if(isset($organizationImg->orgimg) && !empty($organizationImg->orgimg)){
                        $orgLogoImg = DOMAIN.'public/uploads/organisation/'.$organizationImg->orgimg ; 
                    }?>
                    <img class="logo_img" src="<?php echo $orgLogoImg;?>" alt="logo image here"/>
                </span>
            </div>
        </div>
                        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-info">
                    
                    <div class="panel-body">
                        <div class="text-center year_info">
                            <b>WPS Report For <?php echo date('F Y',strtotime($this->empPayslipData[0]['generate_date'])); ?> <br/>
                                <span>(WPS Report generated on <?php echo date('j F Y',strtotime($this->wpsData['created_date'])); ?>)</span>
                            </b>
                        </div>
                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <th width="20%" class="info" colspan="1">Name</th>
                                    <td width="20%" colspan="2"><?php echo $this->employeedata['userfullname']; ?> - <?php echo $this->employeedata['employeeId'];?></td>
                                    <th width="20%" class="info" colspan="1" id="p">Personal No.</th>
                                    <td width="20%" colspan="2"><?php echo $this->employeedata['contactnumber'];?></td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Bank</th>
                                    <td colspan="2"><?php echo strtoupper($this->salarydetails['bankname']); ?></td>
                                    <th class="info" colspan="1">Bank Acc. No. / IBAN / Ref. No.</th>
                                    <td colspan="2"><?php echo $this->salarydetails['accountnumber']?$this->salarydetails['accountnumber']:'-';?></td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Date of Joining</th>
                                    <td colspan="2"><?php echo $this->employeedata['selecteddate'];?></td>
                                    <th class="info" colspan="1">Leaves</th>
                                    <td colspan="2"><?=$lop?></td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Working Days</th>
                                    <td colspan="2">30</td>
                                    <th class="info" colspan="1">Employment Status</th>
                                    <td colspan="2">
                                        <?php echo $this->employeeSummaryData['emp_status_name']?$this->employeeSummaryData['emp_status_name']:'-';?>
                                        <?php if($this->employeeSummaryData['emp_status_id'] == 6 && $this->employeedata['vendor_name']!='') {
                                                    echo "(".$this->employeedata['vendor_name'].")";
                                                } 
                                        ?>
                                    </td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Mode of Salary Transfer</th>
                                    <td colspan="2"> 
                                        <?php
                                            if($this->wpsData['mode_of_salary_transfer'] == 1){
                                                echo 'Bank Transfer';
                                            } else if($this->wpsData['mode_of_salary_transfer'] == 2){
                                                echo 'Cheque';
                                            } else if($this->wpsData['mode_of_salary_transfer'] == 3){
                                                echo 'Cash';
                                            } else if($this->wpsData['mode_of_salary_transfer'] == 4){
                                                echo 'Exchange';
                                            } else {
                                                echo '-';
                                            }
                                        ?>
                                    </td>
                                    <th class="info" colspan="1">Reference No.</th>
                                    <td colspan="2"> <?php echo $this->wpsData['reference_no']?$this->wpsData['reference_no']:'-'; ?> </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
                        <div class="row">
            <div class="col-md-12 table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr class="info">
                            <td>
                                <div class="row">
                                    <div class="col-md-4">
                                        Earnings
                                    </div>
                                    <div class="col-md-2">
                                        Amount
                                    </div>
                                    <div class="col-md-4">
                                        Deduction
                                    </div>
                                    <div class="col-md-2">
                                        Amount
                                    </div>
                                </div>
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="earning_deduct">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="row">
                                            <?php foreach($this->earningColArr as $k => $v):?>
                                            <div class="col-md-8"><?php echo $v['name'];?></div>
                                            <div class="col-md-4 text-left"><?php echo number_format($v['value'],2);?></div>
                                            <?php endforeach;?>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="row">
                                            <?php foreach($this->deductColArr as $k => $v):?>
                                            <div class="col-md-8"><?php echo $v['name'];?></div>
                                            <div class="col-md-4 text-left"><?php echo number_format($v['value'],2);?></div>
                                            <?php endforeach;?>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-8">LOP Amount</div>
                                            <div class="col-md-4 text-left"><?=number_format($deductedSalary,2)?></div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="row">
                                    <div class="col-md-6"><b>Net Earning</b></div>
                                    <div class="col-md-5 text-right" style="margin-left: -20px;"><b><?php echo number_format($netPay,2); echo ' '.$this->currency['currencycode'];?></b></div>
                                </div>
                            </td>
                            
                        </tr>

                    </tbody>
                </table>
                <span>&nbsp;**This is computer generated payslip and require signature and stamp of Bank.</span>
            </div>
        </div>
                    </div>
                </div>
            </div>

            <div class="clear"></div>
            <div style="height:50px !important; width:100% !important;"></div>
            

            <div class="clear"></div>
            <div style="height:50px !important; width:100% !important;"></div>
            
        </div>
        
       
        
        

    </div>	
    </div>
    <div align="center" style="width: 100%; float: left;">
        <input type="button" value="Print" class="print" onclick="printSalarySlip();">
        <!--<input type="button" value="PDF" class="print" onclick="salarySlipPDF();">-->
    </div>
    <div style="clear:both">&nbsp;</div>
    <?php
}
?>
    
<div id="payrollcategoryContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
	    <img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
	</div>

	<iframe id="payrollcategoryCont" class="business_units_iframe" frameborder="0"></iframe>
</div>
    
<script type='text/javascript'>
    $(document).ready(function(){
        $('#value_type').on('change', function () {
            alert(this.value);
            // if (this.value == '1'); { No semicolon and I used === instead of ==
            if (this.value === 'numeric') {
                $("#numeric").show();
                $( "input[name*='numeric']" ).attr("required","required");
            } else {
                $("#numeric").hide();
                $( "input[name*='numeric']" ).removeAttr("required");
            }

            if (this.value === 'formula') {
                $("#formula").show();
                //$( "input[name*='formula']" ).attr("required","required");
            } else {
                $("#formula").hide();
                //$( "input[name*='formula']" )..removeAttr("required");
            }

            if (this.value === 'conditionwithformula'){
             $("#conditionwithformula").show();
             } else {
             $("#conditionwithformula").hide();
             }
        })
    });
    function openForm(type){
       $('#payslip_form').slideToggle('slow');
       $('#payroll_category_type').val(type);
    }
    
    $(document).ready(function () {
        $("#emp_payslips").addClass('active');
        $("#emp_payslips").removeAttr("onclick");
    });
    
    function printSalarySlip(){
        //alert($("#winPrint").html());
        PrintElem($("#winPrint").html());
    }
     function salarySlipPDF(){
        //alert($("#winPrint").html());
      var param_str = $('#filters_div').find('select, textarea, input').serialize();
        var url= base_url+"/default/reports/rolesgrouprptpdf?"+param_str; 	
	$.ajax({
                type: "POST",
                url: base_url +'/emppayslips/printslip/userid/<?php echo $this->id; ?>',
                data: param_str,
                success: function(response) 
                { 
                    alert(response);
                    response = JSON.parse(response);
                    url = base_url +'/reports/downloadreport/file_name/' + response.file_name;
                    var $preparingFileModal = $("#preparing-file-modal");
                    $preparingFileModal.dialog({ modal: true });

                    $.fileDownload(url, {
                            successCallback: function(url) 
                            {
                                $preparingFileModal.dialog('close');
                            },
                            failCallback: function(responseHtml, url) 
                            {
                                $preparingFileModal.dialog('close');
                                $("#error-modal").dialog({ modal: true });
                            }
                        });			        
                    return false; //this is critical to stop the click event which will trigger a normal file download!
                },
        });
    
    }
    function PrintElem(elem)
{
    var mywindow = window.open('', 'PRINT', 'height=400,width=600');

    mywindow.document.write('<html><head><title>Sharad Technologies LLC - School ERP</title><style type="text/css">*{-webkit-print-color-adjust: exact !important; }.col-md-6{width:49% !important; float:left !important;}.text-right{text-align:right !important;}.info,.panel-info>.panel-heading{background-color:#d9edf7 !important;-webkit-print-color-adjust: exact !important; padding: 10px 15px; border-bottom: 1px solid transparent; border-top-left-radius: 3px; border-top-right-radius: 3px;}.newtablegrid table {color: #3B3B3B;font-family: "Roboto Regular";font-size: 13px;line-height: 25px; position: relative;width: 100%;border-collapse: collapse;}.table-bordered {border: 1px solid #ddd; }th,td{border: 1px solid #ddd !important; text-align:left !important; padding:8px !important;}.text-center{text-align:center;}.year_info{padding:20px 10px !important;}</style>');
    mywindow.document.write('</head><body >');
    
    //mywindow.document.write('<h1>Sharad Technologies LLC - School ERP</h1>');
    mywindow.document.head.innerHTML+='<link rel="stylesheet" type="text/css" href="'+base_url+'/public/media/css/bootstrap.min.css" />';
    mywindow.document.write(elem);

    mywindow.document.write('</body></html>');
    
    var tables=mywindow.document.getElementsByTagName('table');
    
    for(var i=0;i<tables.length;i++) {
        tables[i].setAttribute('cellpadding','5');
        tables[i].setAttribute('cellspacing','0');
        tables[i].setAttribute('border','1');
        tables[i].setAttribute('width','100%');
        tables[i].setAttribute('style','margin-top:20px; border-top:0;');
    }
    
    mywindow.document.close(); // necessary for IE >= 10
    mywindow.focus(); // necessary for IE >= 10*/
    
    mywindow.print();
    mywindow.close();

    return true;
}
</script>



