<?php print_r($this->err_msg_arr); ?>
<div style="float: left;">
<?php if(array_key_exists('header_messsage', $this->err_msg_arr)):
    if(isset($this->err_msg_arr['header_messsage'])):?>
    <div class="notification">
    <?php echo $this->err_msg_arr['header_messsage'] ;?>
    </div>    
<?php endif;
endif;?>    
</div>
<h4>Create payroll group</h4><br><hr>
<div class="new-form-ui">
                                <label class="required">Payroll group name</label>
                                <div class="division">
                                    <input name="group_name" id="group_name" value="" class="formDataElement"  type="text" required="required">  
<span id="errors-group_name" class="errors"><?php if(array_key_exists('header_messsage', $this->err_msg_arr)){ echo $this->err_msg_arr['header_messsage'];}?></span>
                                </div> 

                            </div>
<br><h4>Salary Preference</h4><hr>
<div class="new-form-ui">
                                <label class="required">
Employee salary type</label>
                                <div class="division">
                                   Salaried </span>
                                </div> 

                            </div>
<div class="new-form-ui">
                                <label class="required">
Payment frequency</label>
                                <div class="division">
                                    <select><option>Daily</option>
                                    <option>Weekly</option>
                                    <option>Bi-weekly - Once in 2 weeks</option>
                                    <option>Semi monthly - Once in 15 day</option>
                                    <option>Daily</option>
                                    </select>
                                    </span>
                                </div> 

                            </div>
<br><h4>Selected Payroll Categories</h4><hr>
<div id='employee' class='details_data_display_block newtablegrid'>
            <table class='grid' align='center'  width='100%' cellspacing='0' cellpadding='4' border='0'>
                <thead><tr><th width=90><span class='action-text'>Action</span></th>
                        <th width=90><span class='action-text'>Sort</span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Payroll Category</a></span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Code</a> </span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Value</a> </span></th>

                </thead><tbody><tr onclick='selectrow(employee,this);' class='row1'><td ><div class="grid-action-align">
                    Remove							
									</div>
                            </td><td ><span  title='Manak' >Manak</span></td><td ><span  title='Pura' >Pura</span></td><td ><span  title='manak@gmail.com' >manak@gmail.com</span></td><td ><span  title='EMP522' >EMP522</span></td>
	    </table>
    </div>

<br>
<br>
<br>
<h4>Add payroll categories</h4><hr>



        <div id='employee' class='details_data_display_block newtablegrid'>
            <table class='grid' align='center'  width='100%' cellspacing='0' cellpadding='4' border='0'>
                <thead><tr><th width=90><span class='action-text'>Action</span></th>
                        <th width=90><span class='action-text'>Sort</span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Payroll Category</a></span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Code</a> </span></th>
                        <th width=90><span class='action-text'><a href='javascript:void(0);' onclick=javascript:paginationndsorting('/beta/hrm/index.php/payrollgroup/index/sort/ASC/by/firstname/objname/payrollgroup/page/1/per_page/20');> Value</a> </span></th>
   </thead><tbody><tr onclick='selectrow(employee,this);' class='row1'><td ><div class="grid-action-align">
                    Add							
									</div>
                            </td><td ><span  title='Manak' >Manak</span></td><td ><span  title='Pura' >Pura</span></td><td ><span  title='manak@gmail.com' >manak@gmail.com</span></td><td ><span  title='EMP522' >EMP522</span></td>
	    </table>
    </div>
<br>
<br>
<div class="new-form-ui-submit">
					
<input name="submit" id="submitbutton" value="Create payroll group" onclick="saveEmployee()" type="submit">
<button onclick="window.location.href='http://localhost/beta/hrm/index.php/payrollgroup';" type="button" id="Cancel" name="Cancel">Cancel</button>
			</div>