<!DOCTYPE html>
<meta name="robots" content="noindex">
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <span class="text-left"><img src="" alt="logo image here"/></span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-info">
                    <div class="panel-heading">Company Name here</div>
                    <div class="text-center"><b>Payslip For June 2017</b></div>
                    <div class="panel-body">

                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <th class="info" colspan="1">Personal No.</th>
                                    <td colspan="2">1234567890</td>
                                    <th class="info" colspan="1">Name</th>
                                    <td colspan="2">Deepak Gupta</td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Bank</th>
                                    <td colspan="2">1234567890</td>
                                    <th class="info" colspan="1">Bank A/C No.</th>
                                    <td colspan="2">Deepak Gupta</td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">DOJ</th>
                                    <td colspan="2">1234567890</td>
                                    <th class="info" colspan="1">LOP Days</th>
                                    <td colspan="2">Deepak Gupta</td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">PF No.</th>
                                    <td colspan="2">1234567890</td>
                                    <th class="info" colspan="1">STD Days</th>
                                    <td colspan="2">Deepak Gupta</td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Location</th>
                                    <td colspan="2">1234567890</td>
                                    <th class="info" colspan="1">Worked Days</th>
                                    <td colspan="2">Deepak Gupta</td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Department</th>
                                    <td colspan="2">1234567890</td>
                                    <th class="info" colspan="1">Designation</th>
                                    <td colspan="2">Deepak Gupta</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                        <tr class="info">
                            <th class="text-center">Earnings</th>
                            <th class="text-center">Amount NO.</th>
                            <th class="text-center">Deduction</th>
                            <th class="text-center">Amount in RS.</th>
                        </tr>
                    </thead>
                    <tbody>

                        <tr>
                            <td>Basic</td>
                            <td class="text-right">1234567890</td>
                            <td>Provident Fund</td>
                            <td class="text-right">2342342</td>
                        </tr>
                        <tr>
                            <td>Houe Rent allowence</td>
                            <td class="text-right">1234567890</td>
                            <td>Proffesional Tax</td>
                            <td class="text-right">2452423423</td>
                        </tr>
                        <tr>
                            <td>Special Allowenece</td>
                            <td class="text-right">1234567890</td>
                            <td>Income tax</td>
                            <td class="text-right">2342424234</td>
                        </tr>
                        <tr>
                            <td>Hot skill Bonus</td>
                            <td class="text-right">1234567890</td>
                            <td></td>
                            <td class="text-right"></td>
                        </tr>
                        <tr>
                            <td><b>Gross Earning</b></td>
                            <td class="text-right"><b>1234567890</b></td>
                            <td><b>Gross Deduction</b></td>
                            <td class="text-right"><b>4234343</b></td>
                        </tr>
                        <tr>
                            <td></td>
                            <td class="text-right"><b>NET Earning</b></td>
                            <td class="text-left"><b>4234343</b></td>
                            <td></td>
                        </tr>

                    </tbody>
                </table>
                <span>**This is computer generated Payslip and does not require signature and stamp.</span>
            </div>
        </div>
    </div>
</body>

</html>