<?php

/**********

********/
$config['allDbActionArray']=array(
                    'madaan'=>array(
                        'transport_insurance_expiry_notification'=>array('is_action_perform'=>'yes'),
                        'create_back_up_google_drive_per_school'=>array('is_action_perform'=>'yes'),
                        'send_notification_inqueue'=>array('is_action_perform'=>'yes'),
                        'clear_log'=>array('is_action_perform'=>'yes'),
                        'fee_penalty_apply'=>array('is_action_perform'=>'no'),
                        'send_custom_message_to_all_user'=>array('is_action_perform'=>'yes'),
                        'clear_gps_location_data'=>array('is_action_perform'=>'yes'),
                        'erp_delete_by_expire_date'=>array('is_action_perform'=>'no'),
                        'add_outstanding_fee_notfication_que'=>array('is_action_perform'=>'no'),
                        'send_fee_notification_que'=>array('is_action_perform'=>'no'),
                        'full_instance_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                        'full_database_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                    ),
                    'dunes_academy'=>array(
                        'transport_insurance_expiry_notification'=>array('is_action_perform'=>'no'),
                        'create_back_up_google_drive_per_school'=>array('is_action_perform'=>'yes'),
                        'send_notification_inqueue'=>array('is_action_perform'=>'no'),
                        'clear_log'=>array('is_action_perform'=>'yes'),
                        'fee_penalty_apply'=>array('is_action_perform'=>'no'),
                        'send_custom_message_to_all_user'=>array('is_action_perform'=>'no'),
                        'clear_gps_location_data'=>array('is_action_perform'=>'no'),
                        'erp_delete_by_expire_date'=>array('is_action_perform'=>'no'),
                        'add_outstanding_fee_notfication_que'=>array('is_action_perform'=>'no'),
                        'send_fee_notification_que'=>array('is_action_perform'=>'no'),
                        'full_instance_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                        'full_database_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                    ),
                    'gkids'=>array(
                        'transport_insurance_expiry_notification'=>array('is_action_perform'=>'no'),
                        'create_back_up_google_drive_per_school'=>array('is_action_perform'=>'yes'),
                        'send_notification_inqueue'=>array('is_action_perform'=>'no'),
                        'clear_log'=>array('is_action_perform'=>'yes'),
                        'fee_penalty_apply'=>array('is_action_perform'=>'no'),
                        'send_custom_message_to_all_user'=>array('is_action_perform'=>'no'),
                        'clear_gps_location_data'=>array('is_action_perform'=>'no'),
                        'erp_delete_by_expire_date'=>array('is_action_perform'=>'no'),
                        'add_outstanding_fee_notfication_que'=>array('is_action_perform'=>'no'),
                        'send_fee_notification_que'=>array('is_action_perform'=>'no'),
                        'full_instance_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                        'full_database_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                    ),
                    'global_public'=>array(
                        'transport_insurance_expiry_notification'=>array('is_action_perform'=>'no'),
                        'create_back_up_google_drive_per_school'=>array('is_action_perform'=>'yes'),
                        'send_notification_inqueue'=>array('is_action_perform'=>'no'),
                        'clear_log'=>array('is_action_perform'=>'yes'),
                        'fee_penalty_apply'=>array('is_action_perform'=>'no'),
                        'send_custom_message_to_all_user'=>array('is_action_perform'=>'yes'),
                        'clear_gps_location_data'=>array('is_action_perform'=>'no'),
                        'erp_delete_by_expire_date'=>array('is_action_perform'=>'no'),
                        'add_outstanding_fee_notfication_que'=>array('is_action_perform'=>'no'),
                        'send_fee_notification_que'=>array('is_action_perform'=>'no'),
                        'full_instance_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                        'full_database_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                    ),
                    'giis'=>array(
                        'transport_insurance_expiry_notification'=>array('is_action_perform'=>'yes'),
                        'create_back_up_google_drive_per_school'=>array('is_action_perform'=>'yes'),
                        'send_notification_inqueue'=>array('is_action_perform'=>'yes'),
                        'clear_log'=>array('is_action_perform'=>'yes'),
                        'fee_penalty_apply'=>array('is_action_perform'=>'no'),
                        'send_custom_message_to_all_user'=>array('is_action_perform'=>'yes'),
                        'clear_gps_location_data'=>array('is_action_perform'=>'no'),
                        'erp_delete_by_expire_date'=>array('is_action_perform'=>'no'),
                        'add_outstanding_fee_notfication_que'=>array('is_action_perform'=>'no'),
                        'send_fee_notification_que'=>array('is_action_perform'=>'no'),
                        'full_instance_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                        'full_database_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                    ),
                    'ftkacademy'=>array(
                        'transport_insurance_expiry_notification'=>array('is_action_perform'=>'no'),
                        'create_back_up_google_drive_per_school'=>array('is_action_perform'=>'yes'),
                        'send_notification_inqueue'=>array('is_action_perform'=>'no'),
                        'clear_log'=>array('is_action_perform'=>'no'),
                        'fee_penalty_apply'=>array('is_action_perform'=>'yes'),
                        'send_custom_message_to_all_user'=>array('is_action_perform'=>'yes'),
                        'clear_gps_location_data'=>array('is_action_perform'=>'no'),
                        'erp_delete_by_expire_date'=>array('is_action_perform'=>'no'),
                        'add_outstanding_fee_notfication_que'=>array('is_action_perform'=>'no'),
                        'send_fee_notification_que'=>array('is_action_perform'=>'no'),
                        'full_instance_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                        'full_database_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                    ),
                    'demo_ag'=>array(
                        'erp_delete_by_expire_date'=>array('is_action_perform'=>'yes'),
                        'full_instance_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                        'full_database_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                    ),
                    'beta_ag'=>array(
                        'transport_insurance_expiry_notification'=>array('is_action_perform'=>'no'),
                        'create_back_up_google_drive_per_school'=>array('is_action_perform'=>'no'),
                        'send_notification_inqueue'=>array('is_action_perform'=>'no'),
                        'clear_log'=>array('is_action_perform'=>'no'),
                        'fee_penalty_apply'=>array('is_action_perform'=>'no'),
                        'send_custom_message_to_all_user'=>array('is_action_perform'=>'no'),
                        'clear_gps_location_data'=>array('is_action_perform'=>'no'),
                        'erp_delete_by_expire_date'=>array('is_action_perform'=>'no'),
                        'add_outstanding_fee_notfication_que'=>array('is_action_perform'=>'yes'),
                        'send_fee_notification_que'=>array('is_action_perform'=>'yes'),
                        'full_instance_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                        'full_database_backup_at_remote_server'=>array('is_action_perform'=>'yes'),
                    ),
                );

/**
 * 
 * 
 * 
 * 'dam'=>array(
            'transport_insurance_expiry_notification'=>array('is_action_perform'=>'yes'),
            'create_back_up_google_drive_per_school'=>array('is_action_perform'=>'yes'),
            'send_notification_inqueue'=>array('is_action_perform'=>'yes'),
            'clear_log'=>array('is_action_perform'=>'yes'),
            'fee_penalty_apply'=>array('is_action_perform'=>'no'),
            'send_custom_message_to_all_user'=>array('is_action_perform'=>'yes'),
        ),
        ,
        'manor'=>array(
            'transport_insurance_expiry_notification'=>array('is_action_perform'=>'yes'),
            'create_back_up_google_drive_per_school'=>array('is_action_perform'=>'yes'),
            'send_notification_inqueue'=>array('is_action_perform'=>'yes'),
            'clear_log'=>array('is_action_perform'=>'yes'),
            'fee_penalty_apply'=>array('is_action_perform'=>'no'),
            'send_custom_message_to_all_user'=>array('is_action_perform'=>'yes'),
        )
 * 
 * 
 */
//$config['HOST_IP_ADDR']=$_SERVER['SERVER_ADDR'];
?>