<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/payslip_style.css" />
<style type="text/css">
    @media print 
    {
       @page
       {
        size: 8.3in 5.8in;
        size: A5;
        margin: 0;
      }

      html, body {
        width: 8.3in;
        height: 5.8in;
      }

      .earning_deduct{
          display: none !important;
      }
    }
    </style>
<?php
/* * ******************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 * ****************************************************************************** */
?>
 <?php echo $this->headScript()->prependFile(
        $this->baseUrl('\public\scripts\jquery.fileDownload-master\src\Scripts\jquery.fileDownload.js')); ?>
<?php $months = array('1' => 'Jan', '2'=>'Feb', '3'=>'Mar', '4'=>'Apr', '5'=>'May', '6'=>'Jun', '7'=>'Jul', '8'=>'Aug', '9'=>'Sep', '10'=>'Oct', '11'=>'Nov', '12'=>'Dec');?>
<?php if (empty($this->empdata)) { ?>
    <div class="ml-alert-1-info">
        <div class="style-1-icon info"></div>
        <?php if ($this->rowexist == 'norows') { ?>
            No data found.
        <?php } else { ?>
            Employee inactivated.
        <?php } ?>
    </div>
    <?php
} else {
    ?>
    <?php
    $baseUrl = $this->serverUrl() . $this->baseUrl();

    if (!empty($this->employeedata)) {
        echo $this->employeedetails($this->employeedata, 'view', $this->id);
      //echo "<pre>"; print_r($this->employeedata); 
      //print_r($this->salarydetails);
      
    }
    ?>

<!-- Code by Shuchita -->
<?php
    $salaryPerDay=$this->salarydetails['salary']/30;
    $empLeaveData=$this->empLeaveData;

    if($empLeaveData['emp_leave_limit']>=$empLeaveData['used_leaves']) { 
        $lop=0;
    }else{
        $lop=$empLeaveData['used_leaves']-$empLeaveData['emp_leave_limit'];
    }

    $presentDays=30-$lop;
    $salaryForPresentDays=$presentDays*$salaryPerDay;
    $deductedSalary=$salaryPerDay*$lop;
    $netPay=$this->netPayDetails[0]['net_pay']-$deductedSalary;
    
    $doj = $this->doj;
//    $dojLastDayOfMonth = date('t',mktime(0, 0, 0, date('m',strtotime($doj)),10));
//    $joinDate = date('d',strtotime($doj));
//    
//    $workingDays = $dojLastDayOfMonth - $joinDate + 1;
    
    $payslipGenMonth = $this->empPayslipData[0]['payslip_month'];
    $last_day_this_month  = date('t',mktime(0, 0, 0, date('m',strtotime($doj)),10));
    $joinDate = date('d',strtotime($doj));
    if(date('m',strtotime($doj)) == date('m',strtotime('-1 month'))){
        $workingDays = $last_day_this_month - $joinDate + 1;
        $firstDayOfPayslipMonth = date('F j, Y', strtotime($doj));
    } else if(date('m',strtotime($doj)) == $payslipGenMonth && date('Y',strtotime($doj)) == date('Y')) {
        $dojLastDayOfMonth = date('t',mktime(0, 0, 0, date('m',strtotime($doj)),10));
        $workingDays = $dojLastDayOfMonth - $joinDate + 1;
        $firstDayOfPayslipMonth = date('F j, Y', strtotime($doj));
    } 
    else {
        $workingDays = date('t',mktime(0, 0, 0, date('m',strtotime($doj)),10));
        $firstDayOfPayslipMonth = date('F 01, Y',mktime(0, 0, 0, $this->empPayslipData[0]['payslip_month'],10));
    }
?>    

<!-- Code by Shuchita -->


 <div style="width: 100%; float: left; margin-bottom: 20px;">
     <select name="year" id="year" onchange="showPayslipByMonth();">
                <option value="">Select Year</option>
                <?php for($i=2000;$i<=2017;$i++) { ?>
                <option value="<?php echo $i;?>"><?php echo $i;?></option>
                <?php } ?>
            </select>
            <select name="month" id="month" onchange="showPayslipByMonth();">
                <option value="">Select Month</option>
                <?php foreach ($months AS $k => $v):
                    if($k==(date('n'))){
                        break;
                    }
                    if($k<10){
                        $k="0".$k;
                    }?>
                <option value="<?php echo $k;?>"><?php echo $v;?></option>
                <?php endforeach;?>
            </select>
            <input type="hidden" name="emp_id" id="emp_id" value="<?php echo $this->id; ?>">
        </div>
 
<div class="right-block-data right-over-border" style="min-height:0;"> 
        <div id="error_message" style="display:none;"></div>
        <!--<div class="ml-alert-1-info m1-info-set">
                <div class="style-1-icon info"></div>Feature will be available soon.
        </div>-->
        
        <div id="winPrint">
            
            <div class="slimScrollDiv">
                <div id="empleavesummary" class="details_data_display_block newtablegrid" style="width:100% !important;">
                   <div class="row">
        <div class="row">
            <div class="col-md-12 text-center">
                <span>
                    <?php 
                    $organizationImg = new Zend_Session_Namespace('organizationinfo');
                    $hideshowmainmenu = $organizationImg->hideshowmainmenu;
                    $orgLogoImg = MEDIA_PATH.'images/hrms-logo-new.PNG';
                    //echo '$orgLogoImg : '.$orgLogoImg;
                    if(isset($organizationImg->orgimg) && !empty($organizationImg->orgimg)){
                        $orgLogoImg = DOMAIN.'public/uploads/organisation/'.$organizationImg->orgimg ; 
                    }?>
                                     <img src="<?php echo $orgLogoImg;?>" alt="logo image here"/>
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-info">
                    <div class="text-center year_info">
                        <b>Payslip For <?php  echo date('F',mktime(0, 0, 0, $this->empPayslipData[0]['payslip_month'],10)); echo ' '; echo date('Y',strtotime($this->empPayslipData[0]['payslip_year'])); ?> <br/>
                            </b>
                        <?php
                            $prev_month = date('m',mktime(0, 0, 0, $this->empPayslipData[0]['payslip_month'],10));
                            $first_day_this_month = $firstDayOfPayslipMonth;// date('F 01, Y',mktime(0, 0, 0, $this->empPayslipData[0]['payslip_month'],10)); // hard-coded '01' for first day
                            $last_day_this_month  = date('F t, Y',mktime(0, 0, 0, $this->empPayslipData[0]['payslip_month'],10));
                            ?>
                            (<b>Payslip Period: </b><?php echo $first_day_this_month; ?> - <?php echo $last_day_this_month; ?>)
                    </div>
                    <div class="panel-body">

                        <table class="table table-bordered">
                            <tbody>
                                <tr>
                                    <th class="info" colspan="1" id="p">Personal No.</th>
                                    <td colspan="2"><?php echo $this->employeedata['contactnumber'];?></td>
                                    <th class="info" colspan="1">Name</th>
                                    <td colspan="2"><?php echo $this->employeedata['userfullname']; ?></td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Bank Name</th>
                                    <td colspan="2"><?php echo $this->salarydetails['bankname']; ?></td>
                                    <th class="info" colspan="1">Bank A/C No.</th>
                                    <td colspan="2"><?php echo $this->salarydetails['accountnumber']; ?></td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Date of Joining</th>
                                    <td colspan="2"><?php echo $this->employeedata['selecteddate'];?></td>
                                    <th class="info" colspan="1">Leaves</th>
                                    <td colspan="2"><?=$lop?></td>
                                </tr>
                                <tr>
                                    <th class="info" colspan="1">Employee Id</th>
                                    <td colspan="2"><?php echo $this->employeedata['employeeId'];?></td>
                                    <th class="info" colspan="1">Working Days</th>
                                    <td colspan="2"><?php echo $workingDays; ?></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td>
                                <table>
                                    <tr>
                                        <th width='25%'>
                                            Earnings
                                        </th>
                                        <th width='25%'>
                                            Amount
                                        </th>
                                        <th width='25%'>
                                            Deduction
                                        </th>
                                        <th width='25%'>
                                            Amount
                                        </th>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <table>
                                    <tr>
                                        <td width='50%'>
                                            <table>
                                                <tr style="font-weight:bold;">
                                                    <td width='25%'>Basic Salary</td>
                                                    <td width='25%'><?php echo number_format($this->salarydetails['salary'],2);?></td>
                                                </tr>
                                                <?php $p=1; foreach($this->earningColArr as $k => $v):?>
                                                <tr>
                                                    <td width='25%'><?php echo $p==1?'Amount Payable':$v['name'];?></td>
                                                    <td width='25%'><?php echo number_format($v['value'],2);?></td>
                                                </tr>
                                                <?php $p++; endforeach;?>
                                            </table>  
                                        </td>
                                        <td width='50%'>
                                            <table>
                                                <?php foreach($this->deductColArr as $k => $v):?>
                                                <tr>
                                                    <td width='25%'><?php echo $v['name'];?></td>
                                                    <td width='25%'><?php echo number_format($v['value'],2);?></td>
                                                </tr>
                                                <?php endforeach;?>
                                                <tr>
                                                    <td width='25%'>LOP Amount</td>
                                                    <td width='25%'><?=number_format($deductedSalary,2)?></td>
                                                </div>
                                            </table>
                                        </td>
                                    </tr>
                                </table>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <table>
                                    <tr>
                                       <td width='50%'><b>Net Earning</b></td>
                                       <td width='50%'><b><?php echo number_format($netPay,2); echo ' '; echo $this->currency['currencycode'];?></b></td> 
                                    </tr>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <span>**This is computer generated payslip and does not require signature.</span>
            </div>
        </div>
    </div>
                    
                </div>

            </div>

        </div>
        
        
    </div>
    <div class="col-md-12" align="center">
            <input type="button" value="Print" class="print" onclick="printSalarySlip();">
<!--            <input type="button" value="PDF" class="print" onclick="salarySlipPDF();">-->
        </div>
    </div>
    <?php
}
?>
<script type='text/javascript'>
    $(document).ready(function () {
        $("#emp_payslips").addClass('active');
        $("#emp_payslips").removeAttr("onclick");
    });
    
    function printSalarySlip(){
        //alert($("#winPrint").html());
        PrintElem($("#winPrint").html());
    }
     function salarySlipPDF(){
        //alert($("#winPrint").html());
      var param_str = $('#filters_div').find('select, textarea, input').serialize();
        var url= base_url+"/default/reports/rolesgrouprptpdf?"+param_str; 	
	$.ajax({
                type: "POST",
                url: base_url +'/emppayslips/printslip/userid/<?php echo $this->id; ?>',
                data: param_str,
                success: function(response) 
                { 
                    alert(response);
                    response = JSON.parse(response);
                    url = base_url +'/reports/downloadreport/file_name/' + response.file_name;
                    var $preparingFileModal = $("#preparing-file-modal");
                    $preparingFileModal.dialog({ modal: true });

                    $.fileDownload(url, {
                            successCallback: function(url) 
                            {
                                $preparingFileModal.dialog('close');
                            },
                            failCallback: function(responseHtml, url) 
                            {
                                $preparingFileModal.dialog('close');
                                $("#error-modal").dialog({ modal: true });
                            }
                        });			        
                    return false; //this is critical to stop the click event which will trigger a normal file download!
                },
        });
    
    }
   
   function PrintElem(elem)
    {
        var mywindow = window.open('', 'PRINT', 'height=400,width=600,location=no,titlebar=no,toolbar=0,scrollbars=0,status=0');

        mywindow.document.write('<html moznomarginboxes mozdisallowselectionprint><head><title></title><style type="text/css">*{-webkit-print-color-adjust: exact !important; }.info,.panel-info>.panel-heading{background-color:#d9edf7 !important;-webkit-print-color-adjust: exact !important;} th, td{font-size:12px !important; vertical-align: top;} table{vertical-align:text-top !important; border:none !important;}.table-bordered > thead > tr > td, .table-bordered > thead > tr > th{border-bottom-width:0 !important; border-left-width: 0 !important; border-right-width: 0 !important;}</style>');
        mywindow.document.write('<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/bootstrap.min.css" /><link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/payslip_style.css" />'); 
        mywindow.document.write('</head><body >');

        //mywindow.document.write('<h1>Rarome LLC</h1>');

        mywindow.document.write(elem);

        mywindow.document.write('</body></html>');

        var tables=mywindow.document.getElementsByTagName('table');

        for(var i=0;i<tables.length;i++) {
            tables[i].setAttribute('cellpadding','0');
            tables[i].setAttribute('cellspacing','0');
            tables[i].setAttribute('border','0');
            tables[i].setAttribute('width','100%');
            tables[i].setAttribute('style','margin-top:0; border:none; !important;');
        }
        setTimeout(3000);
        mywindow.document.close(); // necessary for IE >= 10
        //    mywindow.focus(); // necessary for IE >= 10*/
        //
        //    mywindow.print();
        //    mywindow.close();

        setTimeout(function(){ mywindow.print(); mywindow.close();}, 3000);

        return true;
    }
   
function showPayslipByMonth(){
        var userid = $('#emp_id').val();
        var month = $('#month').val();
        var year = $('#year').val();
        //alert(userid+'||'+year+'||'+month);
        if(month!='' && year!='') {
            var ajaxURL='<?php echo BASE_URL;?>emppayslips/getpayslipidbymonth';
            $.ajax({
                url:ajaxURL,
                type :'POST',
                data:'year='+year+'&month='+month+'&userid='+userid,
                success:function(msg){ 
                    if(msg > 0) {
                        window.location = '<?php echo BASE_URL;?>emppayslips/view/payslipid/'+msg+'/userid/'+userid;
                    } else {
                        alert('Payslip does not exist for selected month and year.');
                    }
                },
                error: function(xhr, status, error) {
                    var err = eval("(" + xhr.responseText + ")");
                    alert(err.Message);
                  }
            });
        }
    }
</script>
