<style type="text/css">
    #filter{
        margin-bottom: 15px;
    }
</style>

<?php $months = array('1' => 'Jan', '2'=>'Feb', '3'=>'Mar', '4'=>'Apr', '5'=>'May', '6'=>'Jun', '7'=>'Jul', '8'=>'Aug', '9'=>'Sep', '10'=>'Oct', '11'=>'Nov', '12'=>'Dec');?>
<div id="grid_employee" class="all-grid-control">
    <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: 250px; height: auto;">
        <div id="employee1" class="details_data_display_block newtablegrid" style="overflow: hidden; width: 250px; height: auto; padding-bottom: 10px;">
            <table class="grid" width="100%" cellspacing="0" cellpadding="4" border="0" align="center">
                <tr>
                    <td>
                        Select Year : <br />
                        <label>
                            <select name="year" id="year">
                                <?php 
                                    for($i=2000;$i<=date('Y');$i++) {
                                ?>
                                <option value="<?php echo $i;?>"><?php echo $i;?></option>
                                <?php } ?>
                            </select>
                        </label>
                    </td>
                    <td>
                        Select Month : <br />
                        <label>
                            <select name="month" id="month">
                                <?php foreach ($months AS $k => $v):
//                                    if($k==(date('n'))){
//                                        break;
//                                    }
                                    if($k<10){
                                        $k="0".$k;
                                    }?>
                                <option value="<?php echo $k;?>"><?php echo $v;?></option>
                                <?php endforeach;?>
                            </select>
                        </label>
                    </td>
                    <td>
                        Select Role :<br />
                        <label>
                            <select name="roll" id="roll">
                                <option value="">Select role</option>
                                <?php foreach($this->roles AS $k => $v):?>
                                <option value="<?php echo $v['id'];?>"><?php echo $v['rolename'];?></option>
                                <?php endforeach;?>
                            </select>
                        </label>
                    </td>
                   <?php /* <td>
                        Enter the employee name :<br />
                        <label>
                            <!--<input type="text" name="emp_name" id="emp_name" class="formDataElement" />-->
                            <select name="emp_name" id="emp_name">
                                <option value="">Select Employee name</option>
                                <?php foreach($this->all_employees AS $k => $v):?>
                                <option value="<?php echo $v['firstname'].' '.$v['lastname'];?>"><?php echo $v['firstname'].' '.$v['lastname'];?></option>
                                <?php endforeach;?>
                            </select>
                        </label>
                    </td> */?>
                    <td>
                        
                    </td>
                    <!--<td>
                        <input type="button" name="estimate" id="estimate" value="Get next month estimate">
                    </td>-->
                </tr>
            </table>
			
        </div>
        <div class="new-form-ui-submit">
            <input type="button" name="filter" id="filter" value="Search">
        </div>
        <div id="employee" class="details_data_display_block newtablegrid" style="overflow: hidden; width: 250px; height: auto; padding-bottom: 10px;">
        </div>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
    $('#filter').on('click',function(){
        var ajaxURL='<?php echo BASE_URL;?>payslipreport/filter/';
        $.ajax({
            url:ajaxURL,
            type :'POST',
            data:'year='+$('#year').val()+'&month='+$('#month').val()+'&roll='+$('#roll').val()+'&emp_name='+$('#emp_name').val(),
            success:function(msg){
                $('#employee').html(msg);
            }
        });
    });
});
</script>